### POST /register
POST http://localhost:4000/register
Content-Type: application/json

{
  "username": "jack@email.com",
  "password": "1234"
}

### POST /login
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "jack@email.com",
  "password": "1234"
}

### GET /logout
GET http://localhost:4000/logout
